# Run this code in the case that the data has gone corrupt
import functions

functions.genC(*[100, 100, 100])
